# Generated by Django 5.2.4 on 2025-07-28 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_alter_voicesample_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='simple_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='voicesample',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_samples', to='accounts.simple_user'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
